package uz.softcity.backbuild.buildmegaservice.entity.enums;

/**
 * permission class
 */
public enum Permission {
    ADD_USER,
    EDIT_USER,
    DELETE_USER,
    VIEW_USER,

    ADD_ATTACHMENT,
    EDIT_ATTACHMENT,
    DELETE_ATTACHMENT,

    ADD_CATEGORY,
    EDIT_CATEGORY,
    DELETE_CATEGORY,

    ADD_CONSTRUCTION,
    EDIT_CONSTRUCTION,
    DELETE_CONSTRUCTION,

    ADD_CONTACT,
    EDIT_CONTACT,
    DELETE_CONTACT,

    ADD_HISTORY,
    EDIT_HISTORY,
    DELETE_HISTORY,

    ADD_NAVIGATION,
    EDIT_NAVIGATION,
    DELETE_NAVIGATION,

    ADD_NEWS,
    EDIT_NEWS,
    DELETE_NEWS,

    ADD_SERVICE,
    EDIT_SERVICE,
    DELETE_SERVICE,

    ADD_COMMENT,
    EDIT_COMMENT,
    DELETE_COMMENT,

    ADD_CAROUSEL,
    EDIT_CAROUSEL,
    DELETE_CAROUSEL,

    ADD_PROJECT,
    EDIT_PROJECT,
    DELETE_PROJECT,

    ADD_SOCIAL_NETWORK,
    EDIT_SOCIAL_NETWORK,
    DELETE_SOCIAL_NETWORK,

    ADD_SOCIAL_NETWORK_URL,
    EDIT_SOCIAL_NETWORK_URL,
    DELETE_SOCIAL_NETWORK_URL,

    DELETE_USER_COMMENT
}
